project_id = "ktlcoubmzodellhquhgb"

[functions.semantic-search]
verify_jwt = false


[functions.cleanup-documents]
verify_jwt = false

[functions.process-complete-pdf]
verify_jwt = false

[functions.answer-question]
verify_jwt = false
