// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktlcoubmzodellhquhgb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0bGNvdWJtem9kZWxsaHF1aGdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NzY1NTMsImV4cCI6MjA3NDQ1MjU1M30.td3_3Fa6E-u6YcNNu44rfeNJ9l4-v_P0N1N92PM80-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});